### PR TITLE
Massive refactoring

### PR DESCRIPTION
**Pull request by MusicTheorist**
This is a refactored version of Andrey Astrelin's Grail Sort with better spacing, clear and distinct variable names, and superfluous declarations and arguments removed. I also added a "GrailShift" function that acts like Insertion Sort when "GrailRotate" is dealing with lengths adjacent to each other. Hopefully, Grail Sort is more legible and easier to comprehend now.

### CODE REVIEW

**Comment by Morwenn** [comment]
Thanks for the update with clear names and spacing. I've been maintaining a C++ fork of GrailSort and to be honest I never pretended to understand most of the algorithm; this will certainly help :)

**Comment by MusicTheorist** [comment]
> Thanks for the update with clear names and spacing. I've been maintaining a C++ fork of GrailSort and to be honest I never pretended to understand most of the algorithm; this will certainly help :)

You're welcome! Would you like to help author a proper C++ fork of refactored GrailSort? I would really appreciate it. Your commits to WikiSort C++ look outstanding, and I certainly don't have the C++ experience that you do.

**Comment by Morwenn** [comment]
I could surely make a proper C++ fork and repository for GrailSort if I find some time, sure. I would most likely rebase it on your cleanup if I do so.

**Comment by MusicTheorist** [comment]
> I could surely make a proper C++ fork and repository for GrailSort if I find some time, sure. I would most likely rebase it on your cleanup if I do so.

Thanks so much! I'll be making a whole Grail Sort repository with a C/C++, Java, and upcoming Python version.

**Comment by Morwenn** [comment]
Oh, kind of like the WikiSort one? I don't know whether it drives adoption but at least you can make sure that every version benefits from general improvements.

**Comment by MusicTheorist** [comment]
This version is now deprecated!

**Pull request closed without merging**
